import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import AuthContext from './auth/AuthContext'

const fira = Fira_Code({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthContext>
        <body className={`${fira.className} dark`}>{children}</body>
      </AuthContext>
    </html>
  );
}
